"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Bookmark, Check, Copy, ExternalLink, Share2 } from "lucide-react";
import { useSession } from "next-auth/react";
import { formatPostDate, initials, profileUrl } from "@/lib/social";

type Post = { id: string; text: string; images: string[]; createdAt: string };
type Profile = { id: string; name: string | null; username: string; image: string | null; posts: Post[] };

export default function PublicPostClient({ username, postId }: { username: string; postId: string }) {
  const { status } = useSession(); const [profile, setProfile] = useState<Profile | null>(null); const [post, setPost] = useState<Post | null>(null); const [copied, setCopied] = useState(false); const [likes, setLikes] = useState(false); const [bookmarked, setBookmarked] = useState(false); const [loading, setLoading] = useState(true);
  useEffect(() => { if (status !== "authenticated") return; fetch(`/api/users/${encodeURIComponent(username)}`, { cache: "no-store" }).then(async (response) => { const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Not found"); setProfile(data); setPost((data.posts || []).find((item: Post) => item.id === postId) || null); }).catch(() => { setProfile(null); setPost(null); }).finally(() => setLoading(false)); }, [status, username, postId]);
  async function copyLink() { await navigator.clipboard.writeText(window.location.href); setCopied(true); setTimeout(() => setCopied(false), 1800); }
  async function share() { if (navigator.share) { await navigator.share({ title: `${profile?.name || username} on Trust.Me`, url: window.location.href }).catch(() => undefined); return; } copyLink(); }
  if (loading || status === "loading") return <main className="profilePage"><div className="profileLoading">Loading post…</div></main>;
  if (!profile || !post) return <main className="profilePage"><section className="profileGate"><span className="kicker">TRUST.ME</span><h1>This post is unavailable.</h1><p>The post may have been deleted or the link may be incorrect.</p><Link className="primary" href={profileUrl(username)}>View profile</Link></section></main>;
  return <main className="profilePage publicPostPage"><header className="profileNav"><Link className="logo" href="/">Trust<span>.</span>Me</Link><nav><Link href="/assets">Marketplace</Link><Link href="/creators">Creators</Link><Link href="/how-it-works">How it works</Link></nav><Link className="outlineButton" href={profileUrl(profile.username)}>View profile</Link></header><div className="postDetailShell"><Link className="backLink" href={profileUrl(profile.username)}><ArrowLeft size={15}/> Back to @{profile.username}</Link><article className="postDetailCard"><div className="postHead"><Link href={profileUrl(profile.username)}><div className="smallAvatar">{profile.image ? <img src={profile.image} alt=""/> : initials(profile.name || profile.username)}</div></Link><div className="postAuthor"><strong>{profile.name || profile.username} <span className="verifiedDot"><Check size={10}/></span></strong><span>@{profile.username} · {formatPostDate(post.createdAt)}</span></div></div>{post.text && <p className="postDetailText">{post.text}</p>}{post.images.length > 0 && <div className={`postImageGrid count-${Math.min(post.images.length, 4)}`}>{post.images.map((src, i) => <img key={`${post.id}-${i}`} src={src} alt="Post media"/>)}</div>}<div className="postDetailMeta">{formatPostDate(post.createdAt)} · Trust.Me</div><div className="postActions"><button className={likes ? "liked" : ""} onClick={() => setLikes((x) => !x)}>♡ {likes ? "Liked" : "Like"}</button><button>↩ Reply</button><button className={bookmarked ? "saved" : ""} onClick={() => setBookmarked((x) => !x)}><Bookmark size={14}/> {bookmarked ? "Saved" : "Save"}</button><button onClick={share}><Share2 size={14}/> Share</button><button onClick={copyLink}><Copy size={14}/> {copied ? "Copied" : "Copy link"}</button></div></article><div className="permalinkCard"><span className="permalinkIcon"><ExternalLink size={16}/></span><div><strong>Permanent post link</strong><span>Anyone with this URL can return to this exact post.</span></div><button onClick={copyLink}>{copied ? <Check size={15}/> : <ExternalLink size={15}/>}</button></div></div>{copied && <div className="toastNotice"><Check size={15}/> Link copied</div>}</main>;
}
