"use client";

import { useState } from "react";
import SiteHeader from "@/components/site-header";
import { ArrowRight, CheckCircle2, FileCheck2, ShieldCheck } from "lucide-react";

export default function SellPage() {
  const [submitted, setSubmitted] = useState(false);
  return <main><SiteHeader /><section className="sellHero"><div><span className="kicker">SELL WITH TRUST</span><h1>Turn a valuable asset into a <em>verified opportunity.</em></h1><p>Trust.Me helps serious sellers present valuable assets with clarity, documentation, and confidence.</p></div><div className="sellSteps"><div><span>01</span><strong>Submit</strong><p>Tell us what you own.</p></div><div><span>02</span><strong>Verify</strong><p>We review the details.</p></div><div><span>03</span><strong>List</strong><p>Reach serious buyers.</p></div></div></section><section className="sellBody"><div className="sellFormCard">{submitted ? <div className="successState"><CheckCircle2 size={44}/><span className="kicker">REQUEST RECEIVED</span><h2>We&apos;ll take it from here.</h2><p>Your asset enquiry has been recorded. A Trust.Me team member will review the information before the asset can enter verification.</p><button className="secondary" onClick={() => setSubmitted(false)}>Submit another asset</button></div> : <form onSubmit={(e) => { e.preventDefault(); setSubmitted(true); }}><span className="kicker">START YOUR SUBMISSION</span><h2>Tell us about the asset.</h2><p className="formIntro">This first step is an enquiry, not a commitment to list.</p><label>Asset name<input required placeholder="e.g. Waterfront Villa" /></label><label>Asset type<select defaultValue=""><option value="" disabled>Select a type</option><option>Residential</option><option>Commercial</option><option>Land</option><option>Collectible</option><option>Business</option></select></label><label>Location<input required placeholder="City, district or address" /></label><label>Expected price<input required placeholder="e.g. EGP 15,000,000" /></label><label>Your email<input required type="email" placeholder="you@example.com" /></label><label>Notes<textarea placeholder="Anything a verification specialist should know?" rows={4}/></label><button className="primary submitBtn" type="submit">Begin verification enquiry <ArrowRight size={17}/></button></form>}</div><aside className="sellAside"><div className="asideIcon"><ShieldCheck size={25}/></div><h3>Verification before visibility.</h3><p>We designed the seller journey to put trust before exposure.</p><ul><li><FileCheck2/> Documentation reviewed</li><li><ShieldCheck/> Ownership information checked</li><li><CheckCircle2/> Clear listing standards</li></ul></aside></section></main>;
}
