import Link from "next/link";
import { ArrowRight, CheckCircle2, FileCheck2, Search, ShieldCheck, UserCheck } from "lucide-react";
import SiteHeader from "@/components/site-header";

const steps = [
  { icon: Search, number: "01", title: "Explore", text: "Browse valuable assets through a marketplace designed around clear information, not noise." },
  { icon: FileCheck2, number: "02", title: "Review", text: "Open the Asset Passport to understand the asset, seller status, key facts, and verification trail." },
  { icon: UserCheck, number: "03", title: "Connect", text: "When you find the right opportunity, submit an enquiry and move into a serious buyer conversation." },
  { icon: ShieldCheck, number: "04", title: "Transact", text: "Verification is designed to create a stronger information foundation before a transaction proceeds." },
];

export default function HowItWorksPage() { return <main><SiteHeader /><section className="simpleHero"><span className="kicker">THE TRUST.ME STANDARD</span><h1>Trust is not a badge.<br/><em>It is a process.</em></h1><p>We are building a marketplace where valuable assets are presented with the information buyers need to make more confident decisions.</p></section><section className="processSection"><div className="processIntro"><span className="kicker">HOW IT WORKS</span><h2>From discovery to <em>confidence.</em></h2></div><div className="processGrid">{steps.map(({icon: Icon, number, title, text}) => <article key={number} className="processCard"><div className="processIcon"><Icon size={22}/></div><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="standardBand"><div><span className="kicker">ASSET PASSPORT</span><h2>One record.<br/><em>Clearer decisions.</em></h2></div><div><p>The Asset Passport is the product layer that brings ownership information, documentation status, asset facts, and verification into one structured view.</p><Link className="primary" href="/assets">Explore verified assets <ArrowRight size={17}/></Link></div></section><section className="faqSection"><span className="kicker">GOOD TO KNOW</span><h2>Built for <em>clarity.</em></h2><div className="faqGrid"><div><strong>What does “verified” mean?</strong><p>It means Trust.Me has reviewed the information required by our listing standard. It is not a substitute for independent legal, financial, or professional advice.</p></div><div><strong>Can anyone list an asset?</strong><p>Anyone can submit an enquiry. Assets are only published after they pass the applicable verification process.</p></div><div><strong>Is Trust.Me the transaction itself?</strong><p>Trust.Me is the marketplace and information layer. Specific transaction terms and professional due diligence remain part of the buyer and seller process.</p></div><div><strong>What comes next?</strong><p>We are building the infrastructure for offers, saved assets, creator distribution, secure accounts, and transaction workflows.</p></div></div></section></main>; }
