"use client";

import Link from "next/link";
import { Search, Check, UserPlus } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useSession } from "next-auth/react";
import { profileUrl } from "@/lib/social";

type Person = { id: string; name: string | null; username: string; image: string | null; bio: string; verified: boolean; followers: number; following: number; postCount: number; isFollowing: boolean };
function initials(name: string) { return name.split(/\s+/).slice(0, 2).map((x) => x[0]).join("").toUpperCase() || "T"; }

export default function PeoplePage() {
  const { status } = useSession(); const [query, setQuery] = useState(""); const [sort, setSort] = useState("Popular"); const [peopleSource, setPeopleSource] = useState<Person[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  async function load() { setLoading(true); try { const response = await fetch(`/api/users${query ? `?q=${encodeURIComponent(query)}` : ""}`, { cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Couldn't load people."); setPeopleSource(data); setError(""); } catch (err) { setError(err instanceof Error ? err.message : "Couldn't load people."); } finally { setLoading(false); } }
  useEffect(() => { if (status === "authenticated") load(); }, [status]);
  const people = useMemo(() => { const list = peopleSource.filter(p => `${p.name || ""} ${p.username}`.toLowerCase().includes(query.toLowerCase())); if (sort === "New") return [...list].sort((a,b) => b.username.localeCompare(a.username)); if (sort === "Active") return [...list].sort((a,b) => b.postCount-a.postCount); if (sort === "Verified") return list.filter(p => p.verified); return [...list].sort((a,b) => b.followers-a.followers); }, [peopleSource, query, sort]);
  async function toggle(person: Person) { const next = !person.isFollowing; setPeopleSource((current) => current.map(p => p.id === person.id ? { ...p, isFollowing: next, followers: p.followers + (next ? 1 : -1) } : p)); try { const response = await fetch(`/api/users/${encodeURIComponent(person.username)}/follow`, { method: next ? "POST" : "DELETE" }); if (!response.ok) throw new Error(); } catch { setPeopleSource((current) => current.map(p => p.id === person.id ? { ...p, isFollowing: !next, followers: p.followers + (next ? -1 : 1) } : p)); } }
  if (status === "loading") return <main className="peoplePage"><div className="profileLoading">Loading people…</div></main>;
  return <main className="peoplePage"><header className="peopleHead"><div><span className="kicker">TRUST.ME NETWORK</span><h1>People</h1><p>The people shaping the Trust.Me network. Discover thoughtful members, verified voices and profiles worth following.</p></div><div className="searchPeople"><Search size={16}/><input value={query} onChange={e => setQuery(e.target.value)} onKeyDown={e => e.key === "Enter" && load()} placeholder="Search people" aria-label="Search people"/></div></header><div className="peopleToolbar"><div className="sortTabs">{["Popular", "Active", "Verified", "New"].map(x => <button key={x} className={sort === x ? "active" : ""} onClick={() => setSort(x)}>{x}</button>)}</div><span className="resultCount">{people.length} members</span></div><section className="peopleRows">{loading ? <div className="emptyState"><h2>Loading people…</h2></div> : error ? <div className="emptyState"><h2>Couldn't load people.</h2><p>{error}</p><button className="primary" onClick={load}>Try again</button></div> : people.length === 0 ? <div className="emptyState"><h2>No people found.</h2><p>There are no other Trust.Me members matching this search yet.</p></div> : people.map((person, index) => <div className="peopleRow" key={person.id}><span className="rankNo">{String(index + 1).padStart(2, "0")}</span><Link href={profileUrl(person.username)} className="personAvatar">{person.image ? <img src={person.image} alt=""/> : initials(person.name || person.username)}</Link><div className="personMeta"><Link href={profileUrl(person.username)}><strong>{person.name || person.username} {person.verified && <span className="verifiedDot"><Check size={9}/></span>}</strong></Link><span>@{person.username}</span><div className="peopleBio">{person.bio}</div></div><div className="followCount"><strong>{person.followers}</strong> followers</div><button className={person.isFollowing ? "followingButton" : "followButton"} onClick={() => toggle(person)}>{person.isFollowing ? <><Check size={12}/> Following</> : <><UserPlus size={12}/> Follow</>}</button></div>)}</section></main>;
}
